# Docker Compose設定（CPU版 - Claude APIのみ）

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yaml-template-lp:latest
    container_name: yaml-lp-app
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # 最小限の環境変数設定（ビルドエラー回避）
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-your_anthropic_api_key_here}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:changeme@database:5432/yaml_lp_db}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_dummy_key_for_build}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-pk_test_dummy_key_for_build}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:-pk_test_dummy_key_for_build}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL:-http://localhost:6379}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN:-dummy_token_for_build}
    volumes:
      # ログやデータの永続化
      - ./logs:/app/logs
      - ./reports:/app/reports
      # モデルキャッシュ（オプション）
      - model-cache:/app/.cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: yaml-lp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: yaml_lp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  model-cache:
    driver: local
  postgres-data:
    driver: local

networks:
  default:
    name: yaml-lp-network
